
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oc ssc
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c0top = new javax.swing.JComboBox();
        c0back = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        c0left = new javax.swing.JComboBox();
        c1top = new javax.swing.JComboBox();
        c1back = new javax.swing.JComboBox();
        c2top = new javax.swing.JComboBox();
        c2back = new javax.swing.JComboBox();
        c2right = new javax.swing.JComboBox();
        c3left = new javax.swing.JComboBox();
        c3top = new javax.swing.JComboBox();
        c4top = new javax.swing.JComboBox();
        c5top = new javax.swing.JComboBox();
        c5right = new javax.swing.JComboBox();
        c8right = new javax.swing.JComboBox();
        c9left = new javax.swing.JComboBox();
        c9back = new javax.swing.JComboBox();
        c10back = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        c6front = new javax.swing.JComboBox();
        c7top = new javax.swing.JComboBox();
        c7front = new javax.swing.JComboBox();
        c6top = new javax.swing.JComboBox();
        c6left = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        c8top = new javax.swing.JComboBox();
        c8front = new javax.swing.JComboBox();
        c17left = new javax.swing.JComboBox();
        c17back = new javax.swing.JComboBox();
        c17bottom = new javax.swing.JComboBox();
        c18back = new javax.swing.JComboBox();
        c18bottom = new javax.swing.JComboBox();
        c19back = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        c14front = new javax.swing.JComboBox();
        c15front = new javax.swing.JComboBox();
        c11back = new javax.swing.JComboBox();
        c11right = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        c16right = new javax.swing.JComboBox();
        c16front = new javax.swing.JComboBox();
        c23bottom = new javax.swing.JComboBox();
        c24front = new javax.swing.JComboBox();
        c24bottom = new javax.swing.JComboBox();
        c25bottom = new javax.swing.JComboBox();
        c19bottom = new javax.swing.JComboBox();
        c19right = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        c21bottom = new javax.swing.JComboBox();
        c22right = new javax.swing.JComboBox();
        c22bottom = new javax.swing.JComboBox();
        c20left = new javax.swing.JComboBox();
        c20bottom = new javax.swing.JComboBox();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        c23left = new javax.swing.JComboBox();
        c23front = new javax.swing.JComboBox();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        c13right = new javax.swing.JComboBox();
        c14left = new javax.swing.JComboBox();
        c12left = new javax.swing.JComboBox();
        jLabel69 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        c25right = new javax.swing.JComboBox();
        c25front = new javax.swing.JComboBox();
        jLabel79 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        btnSolve = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c0top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c0top, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 38, -1, -1));

        c0back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c0back, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 64, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Top");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 38, 30, 20));

        jLabel2.setText("Top");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 30, 20));

        jLabel3.setText("Left");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 30, 20));

        jLabel4.setText("Right");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 30, 20));

        jLabel5.setText("Back");
        jLabel5.setToolTipText("");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 30, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Left");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 90, 30, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Back");
        jLabel7.setToolTipText("");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 64, 30, 20));

        jLabel8.setText("Top");
        jLabel8.setToolTipText("");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 30, 20));

        jLabel9.setText("Top");
        jLabel9.setToolTipText("");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 206, 30, 20));

        jLabel10.setText("back");
        jLabel10.setToolTipText("");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 168, 30, 20));

        jLabel11.setText("Top");
        jLabel11.setToolTipText("");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 30, 20));

        jLabel12.setText("Right");
        jLabel12.setToolTipText("");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 30, 20));

        jLabel13.setText("Top");
        jLabel13.setToolTipText("");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 137, 30, 20));

        c0left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c0left, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 90, -1, -1));

        c1top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c1top, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 137, -1, -1));

        c1back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c1back, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 168, -1, -1));

        c2top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c2top, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 206, -1, -1));

        c2back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c2back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        c2right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c2right, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        c3left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c3left, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        c3top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c3top, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        c4top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green" }));
        getContentPane().add(c4top, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        c5top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c5top, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        c5right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c5right, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        c8right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c8right, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 223, -1, -1));

        c9left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c9left, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 297, -1, -1));

        c9back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c9back, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 328, -1, -1));

        c10back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow" }));
        getContentPane().add(c10back, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 366, -1, -1));

        jLabel14.setText("Left");
        jLabel14.setToolTipText("");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 64, 30, 20));

        jLabel16.setText("Top");
        jLabel16.setToolTipText("");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 30, 20));

        jLabel17.setText("Front");
        jLabel17.setToolTipText("");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 154, 30, 20));

        jLabel18.setText("Back");
        jLabel18.setToolTipText("");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 366, 30, 20));

        jLabel20.setText("Top");
        jLabel20.setToolTipText("");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 128, 30, 20));

        c6front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c6front, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 90, -1, -1));

        c7top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c7top, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 128, -1, -1));

        c7front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c7front, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 154, -1, -1));

        c6top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c6top, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 38, -1, -1));

        c6left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c6left, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 64, -1, -1));

        jLabel21.setText("Top");
        jLabel21.setToolTipText("");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 38, 30, 20));

        jLabel22.setText("Left");
        jLabel22.setToolTipText("");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 297, 30, 20));

        jLabel23.setText("Back");
        jLabel23.setToolTipText("");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 328, 30, 20));

        jLabel24.setText("Right");
        jLabel24.setToolTipText("");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 223, 30, 20));

        jLabel25.setText("Front");
        jLabel25.setToolTipText("");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 30, 20));

        jLabel26.setText("Front");
        jLabel26.setToolTipText("");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 90, 30, 20));

        c8top.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "green", "red", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c8top, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        c8front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c8front, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        c17left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c17left, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        c17back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c17back, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        c17bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c17bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        c18back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c18back, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        c18bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c18bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        c19back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c19back, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));

        jLabel27.setText("Right");
        jLabel27.setToolTipText("");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 30, 20));

        jLabel28.setText("Bottom");
        jLabel28.setToolTipText("");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 40, 20));

        jLabel29.setText("Right");
        jLabel29.setToolTipText("");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 30, 20));

        jLabel30.setText("Front");
        jLabel30.setToolTipText("");
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 30, 20));

        jLabel31.setText("Back");
        jLabel31.setToolTipText("");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 30, 20));

        jLabel32.setText("Back");
        jLabel32.setToolTipText("");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 30, 20));

        jLabel33.setText("Front");
        jLabel33.setToolTipText("");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 30, 20));

        c14front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c14front, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        c15front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white" }));
        getContentPane().add(c15front, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        c11back.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yellow", "green", "red", "orange", "blue", "white" }));
        getContentPane().add(c11back, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 414, -1, -1));

        c11right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c11right, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 445, -1, -1));

        jLabel34.setText("Left");
        jLabel34.setToolTipText("");
        jLabel34.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 30, 20));

        jLabel35.setText("Back");
        jLabel35.setToolTipText("");
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 30, 20));

        jLabel36.setText("Bottom");
        jLabel36.setToolTipText("");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 40, 20));

        jLabel37.setText("Left");
        jLabel37.setToolTipText("");
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 30, 20));

        jLabel38.setText("Front");
        jLabel38.setToolTipText("");
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 30, 20));

        jLabel39.setText("Left");
        jLabel39.setToolTipText("");
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 30, 20));

        c16right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c16right, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        c16front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c16front, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        c23bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c23bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        c24front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c24front, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, -1));

        c24bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c24bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));

        c25bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c25bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, -1, -1));

        c19bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c19bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        c19right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c19right, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        jLabel40.setText("Bottom");
        jLabel40.setToolTipText("");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 40, 20));

        jLabel41.setText("Bottom");
        jLabel41.setToolTipText("");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 40, 20));

        jLabel42.setText("Left");
        jLabel42.setToolTipText("");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 30, 20));

        jLabel43.setText("Bottom");
        jLabel43.setToolTipText("");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 40, 20));

        jLabel44.setText("Right");
        jLabel44.setToolTipText("");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 30, 20));

        jLabel45.setText("Right");
        jLabel45.setToolTipText("");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 30, 20));

        jLabel46.setText("Right");
        jLabel46.setToolTipText("");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 30, 20));

        c21bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue" }));
        getContentPane().add(c21bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        c22right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c22right, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        c22bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c22bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));

        c20left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c20left, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));

        c20bottom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "green", "red", "yellow", "orange", "white" }));
        getContentPane().add(c20bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        jLabel47.setText("Left");
        jLabel47.setToolTipText("");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 30, 20));

        jLabel48.setText("Front");
        jLabel48.setToolTipText("");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 30, 20));

        jLabel49.setText("Bottom");
        jLabel49.setToolTipText("");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 40, 20));

        jLabel50.setText("Bottom");
        jLabel50.setToolTipText("");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 310, -1, 20));

        jLabel51.setText("Front");
        jLabel51.setToolTipText("");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 30, 20));

        jLabel52.setText("Bottom");
        jLabel52.setToolTipText("");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 40, 20));

        c23left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c23left, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        c23front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c23front, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        jLabel53.setText("C0");
        jLabel53.setToolTipText("");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 31, 20));

        jLabel54.setText("C1");
        jLabel54.setToolTipText("");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 31, 20));

        jLabel55.setText("C2");
        jLabel55.setToolTipText("");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, 31, 20));

        jLabel56.setText("C3");
        jLabel56.setToolTipText("");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 31, 20));

        jLabel57.setText("C5");
        jLabel57.setToolTipText("");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 31, 20));

        jLabel58.setText("C4");
        jLabel58.setToolTipText("");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 31, 20));

        jLabel59.setText("C6");
        jLabel59.setToolTipText("");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 64, 23, 20));

        jLabel60.setText("C12");
        jLabel60.setToolTipText("");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 31, 20));

        jLabel61.setText("C7");
        jLabel61.setToolTipText("");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 146, 21, 20));

        jLabel62.setText("C8");
        jLabel62.setToolTipText("");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 223, 21, 20));

        jLabel63.setText("C14");
        jLabel63.setToolTipText("");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 31, 20));

        jLabel64.setText("C15");
        jLabel64.setToolTipText("");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 31, 20));

        jLabel65.setText("C13");
        jLabel65.setToolTipText("");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 31, 20));

        jLabel66.setText("C17");
        jLabel66.setToolTipText("");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 31, 20));

        jLabel67.setText("C9");
        jLabel67.setToolTipText("");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 313, 31, 20));

        jLabel68.setText("C10");
        jLabel68.setToolTipText("");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 366, 31, 20));

        jLabel19.setText("Back");
        jLabel19.setToolTipText("");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 414, 30, 20));

        jLabel70.setText("Right");
        jLabel70.setToolTipText("");
        jLabel70.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 445, 30, 20));

        jLabel71.setText("C11");
        jLabel71.setToolTipText("");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 445, 31, 20));

        c13right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange" }));
        getContentPane().add(c13right, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        c14left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "yellow", "orange", "blue", "white" }));
        getContentPane().add(c14left, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        c12left.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red" }));
        getContentPane().add(c12left, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 60, -1));

        jLabel69.setText("C16");
        jLabel69.setToolTipText("");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 31, 20));

        jLabel72.setText("C18");
        jLabel72.setToolTipText("");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 31, 20));

        jLabel73.setText("C24");
        jLabel73.setToolTipText("");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 31, 20));

        jLabel74.setText("C19");
        jLabel74.setToolTipText("");
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 31, 20));

        jLabel75.setText("C21");
        jLabel75.setToolTipText("");
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 31, 20));

        jLabel76.setText("C23");
        jLabel76.setToolTipText("");
        getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 31, 20));

        jLabel77.setText("C20");
        jLabel77.setToolTipText("");
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 31, 20));

        jLabel78.setText("C25");
        jLabel78.setToolTipText("");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 31, 20));

        jLabel80.setText("C22");
        jLabel80.setToolTipText("");
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 31, 20));

        c25right.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orange", "green", "red", "yellow", "blue", "white" }));
        getContentPane().add(c25right, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, -1, -1));

        c25front.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "white", "green", "red", "yellow", "orange", "blue", " " }));
        getContentPane().add(c25front, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, -1, -1));

        jLabel79.setText("Bottom");
        jLabel79.setToolTipText("");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 490, -1, 20));

        jLabel81.setText("Front");
        jLabel81.setToolTipText("");
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 30, 20));

        btnSolve.setLabel("Solve");
        btnSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, -1, -1));

        jLabel15.setBackground(new java.awt.Color(153, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 0));
        jLabel15.setText("Developed By: Maj Wazed,sigs");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, 200, 40));

        jLabel82.setText("C7");
        getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        jLabel83.setText("C3");
        getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        jLabel84.setText("C0");
        getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel85.setText("C4");
        getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        jLabel86.setText("C5");
        getContentPane().add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        jLabel87.setText("C6");
        getContentPane().add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        jLabel88.setText("C1");
        getContentPane().add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        jLabel89.setText("C8");
        getContentPane().add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));

        jLabel90.setText("C9");
        getContentPane().add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        jLabel91.setText("C2");
        getContentPane().add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jLabel92.setText("C11");
        getContentPane().add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));

        jLabel93.setText("C12");
        getContentPane().add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        jLabel94.setText("C13");
        getContentPane().add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        jLabel95.setText("C14");
        getContentPane().add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        jLabel96.setText("C15");
        getContentPane().add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, -1));

        jLabel97.setText("C16");
        getContentPane().add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        jLabel98.setText("C10");
        getContentPane().add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        jLabel99.setText("C24");
        getContentPane().add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        jLabel100.setText("C20");
        getContentPane().add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, -1, -1));

        jLabel101.setText("C17");
        getContentPane().add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jLabel102.setText("C21");
        getContentPane().add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        jLabel103.setText("C22");
        getContentPane().add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        jLabel104.setText("C23");
        getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, -1, -1));

        jLabel105.setText("C18");
        getContentPane().add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        jLabel106.setText("C25");
        getContentPane().add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        jLabel107.setText("C19");
        getContentPane().add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jLabel108.setText("Bottom Layer");
        getContentPane().add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, -1));

        jLabel109.setText("Top Layer");
        getContentPane().add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel110.setText("Middle Layer");
        getContentPane().add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        jLabel111.setText("Cube No Convention");
        getContentPane().add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        jLabel112.setText("Hold cube's green center top and white center towards you");
        getContentPane().add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSolveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });

        
    }
    public cubbis getItem(int posn){
        cubbis cube=new cubbis();
        if(posn==0){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c0top.getSelectedItem());
            cube.setbackcolor((String)c0back.getSelectedItem());
            cube.setleftcolor((String)c0left.getSelectedItem());
        }else if(posn==1){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c1top.getSelectedItem());
            cube.setbackcolor((String)c1back.getSelectedItem());
            
        }else if(posn==2){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c2top.getSelectedItem());
            cube.setbackcolor((String)c2back.getSelectedItem());
            cube.setrightcolor((String)c2right.getSelectedItem());
        }else if(posn==3){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c3top.getSelectedItem());            
            cube.setleftcolor((String)c3left.getSelectedItem());
        }else if(posn==4){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c4top.getSelectedItem());
           
        }else if(posn==5){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c5top.getSelectedItem());           
            cube.setrightcolor((String)c5right.getSelectedItem());
        }else if(posn==6){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c6top.getSelectedItem());           
            cube.setleftcolor((String)c6left.getSelectedItem());
            cube.setfrontcolor((String)c6front.getSelectedItem());
        }else if(posn==7){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c7top.getSelectedItem());           
            cube.setfrontcolor((String)c7front.getSelectedItem());
        }else if(posn==8){
            cube.setcurposn(posn);        
            cube.settopcolor((String)c8top.getSelectedItem());           
            cube.setrightcolor((String)c8right.getSelectedItem());
            cube.setfrontcolor((String)c8front.getSelectedItem());
        }else if(posn==9){
            cube.setcurposn(posn);        
            cube.setbackcolor((String)c9back.getSelectedItem());           
            cube.setleftcolor((String)c9left.getSelectedItem());
        }else if(posn==10){
            cube.setcurposn(posn);        
            cube.setbackcolor((String)c10back.getSelectedItem());           
           
        }else if(posn==11){
            cube.setcurposn(posn);        
            cube.setbackcolor((String)c11back.getSelectedItem());           
            cube.setrightcolor((String)c11right.getSelectedItem());
        }else if(posn==12){
            cube.setcurposn(posn);                     
            cube.setleftcolor((String)c12left.getSelectedItem());
        }else if(posn==13){
            cube.setcurposn(posn);                       
            cube.setrightcolor((String)c13right.getSelectedItem());
        }else if(posn==14){
            cube.setcurposn(posn);        
            cube.setfrontcolor((String)c14front.getSelectedItem());           
            cube.setleftcolor((String)c14left.getSelectedItem());
        }else if(posn==15){
            cube.setcurposn(posn);        
            cube.setfrontcolor((String)c15front.getSelectedItem());           
            
        }else if(posn==16){
            cube.setcurposn(posn);        
            cube.setfrontcolor((String)c16front.getSelectedItem());           
            cube.setrightcolor((String)c16right.getSelectedItem());
        }else if(posn==17){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c17bottom.getSelectedItem());           
            cube.setleftcolor((String)c17left.getSelectedItem());
            cube.setbackcolor((String)c17back.getSelectedItem());
        }else if(posn==18){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c18bottom.getSelectedItem());           
            cube.setbackcolor((String)c18back.getSelectedItem());
        }else if(posn==19){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c19bottom.getSelectedItem());           
            cube.setrightcolor((String)c19right.getSelectedItem());
            cube.setbackcolor((String)c19back.getSelectedItem());
        }else if(posn==20){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c20bottom.getSelectedItem());           
            cube.setleftcolor((String)c20left.getSelectedItem());
        }else if(posn==21){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c21bottom.getSelectedItem());           
           
        }else if(posn==22){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c22bottom.getSelectedItem());           
            cube.setrightcolor((String)c22right.getSelectedItem());
        }else if(posn==23){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c23bottom.getSelectedItem());           
            cube.setleftcolor((String)c23left.getSelectedItem());
            cube.setfrontcolor((String)c23front.getSelectedItem());
        }else if(posn==24){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c24bottom.getSelectedItem());           
            cube.setfrontcolor((String)c24front.getSelectedItem());
        }else if(posn==25){
            cube.setcurposn(posn);        
            cube.setbottomcolor((String)c25bottom.getSelectedItem());           
            cube.setrightcolor((String)c25right.getSelectedItem());
            cube.setfrontcolor((String)c25front.getSelectedItem());
        }
        
        return cube;
    }
    public void pressContinue(rubiks rb){
       
        btnSolve.addActionListener(new ActionListener(){
           

            @Override
            public void actionPerformed(ActionEvent e) {
                initCube(rb);
                rb.solveRubik();
//                rb.showstatus();
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                
            }
        });
    }
    public void initCube(rubiks rb){
        for(int i=0;i<26;i++){
            cubbis cube=new cubbis();
            cube=this.getItem(i);
            rb.currentarray.add(cube);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnSolve;
    private javax.swing.JComboBox c0back;
    private javax.swing.JComboBox c0left;
    private javax.swing.JComboBox c0top;
    private javax.swing.JComboBox c10back;
    private javax.swing.JComboBox c11back;
    private javax.swing.JComboBox c11right;
    private javax.swing.JComboBox c12left;
    private javax.swing.JComboBox c13right;
    private javax.swing.JComboBox c14front;
    private javax.swing.JComboBox c14left;
    private javax.swing.JComboBox c15front;
    private javax.swing.JComboBox c16front;
    private javax.swing.JComboBox c16right;
    private javax.swing.JComboBox c17back;
    private javax.swing.JComboBox c17bottom;
    private javax.swing.JComboBox c17left;
    private javax.swing.JComboBox c18back;
    private javax.swing.JComboBox c18bottom;
    private javax.swing.JComboBox c19back;
    private javax.swing.JComboBox c19bottom;
    private javax.swing.JComboBox c19right;
    private javax.swing.JComboBox c1back;
    private javax.swing.JComboBox c1top;
    private javax.swing.JComboBox c20bottom;
    private javax.swing.JComboBox c20left;
    private javax.swing.JComboBox c21bottom;
    private javax.swing.JComboBox c22bottom;
    private javax.swing.JComboBox c22right;
    private javax.swing.JComboBox c23bottom;
    private javax.swing.JComboBox c23front;
    private javax.swing.JComboBox c23left;
    private javax.swing.JComboBox c24bottom;
    private javax.swing.JComboBox c24front;
    private javax.swing.JComboBox c25bottom;
    private javax.swing.JComboBox c25front;
    private javax.swing.JComboBox c25right;
    private javax.swing.JComboBox c2back;
    private javax.swing.JComboBox c2right;
    private javax.swing.JComboBox c2top;
    private javax.swing.JComboBox c3left;
    private javax.swing.JComboBox c3top;
    private javax.swing.JComboBox c4top;
    private javax.swing.JComboBox c5right;
    private javax.swing.JComboBox c5top;
    private javax.swing.JComboBox c6front;
    private javax.swing.JComboBox c6left;
    private javax.swing.JComboBox c6top;
    private javax.swing.JComboBox c7front;
    private javax.swing.JComboBox c7top;
    private javax.swing.JComboBox c8front;
    private javax.swing.JComboBox c8right;
    private javax.swing.JComboBox c8top;
    private javax.swing.JComboBox c9back;
    private javax.swing.JComboBox c9left;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
